### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by sarfrazeteam** [HU-BCS1/islamic-inheritance-calculator#7]
AOA,

Thanks for awesome library in the first place!

We are using this package and it works correctly. However, we are unable to get calculations for some relationships, for example, we are not able to get any results for **Paternal Nephew’s sons**. We are using following code:

This works fine:

````
var calculator = require('@hu-bcs1/islamic-inheritance-calculator');
const result = calculator.calculate({ wife: 3, son: 1, daughter: 1 })
console.log(result);
````

This does not work, results empty array:

````
var calculator = require('@hu-bcs1/islamic-inheritance-calculator');
const result = calculator.calculate({ paternal_newphews_son: 1 })
console.log(result);
````

Note that `import { defaultHeirs, calculate } from 'islamic-inheritance-calculator'` didn't work for us so we changed to `var calculator = require('@hu-bcs1/islamic-inheritance-calculator');`. 

So can you please tell us how do we get calculations for **Paternal Nephew’s sons** (and some others not working) ? We can see that this relationship is working fine on your demo site:

http://inheritance.ilmsummit.org/projects/inheritance/home.aspx

Thanks for the help!

**Comment by ducaale** [comment]
وعليكم السلام 

>So can you please tell us how do we get calculations for Paternal Nephew’s sons (and some others not working) ? We can see that this relationship is working fine on your demo site:
>
> http://inheritance.ilmsummit.org/projects/inheritance/home.aspx

I am not affiliated with the site you mentioned. I've only used its test suite on this library. https://inheritance-calculator.netlify.com/ is the website where this library is being used.

The main reason this library doesn't include **Paternal Nephew’s sons** is because they could be affectively treated as Paternal Nephews. This is similar to how the son's son's son would be treated like the son's son if the latter is not alive.

Lastly, this library is a WIP (as can be seen in the README.md) and hasn't been verified by an imam yet. For that reason, I urge you not to use it in a real setting for the fear it might yield incorrect results.

 اللهم هل بلّغت.. اللهم فاشهد

**Comment by sarfrazeteam** [comment]
Thanks.

Any idea of how can we get inheritance code from http://inheritance.ilmsummit.org/projects/inheritance/home.aspx library ? I checked its souce but could not find any javascript used for calculations.

**Comment by ducaale** [comment]
Have you tried contacting the authors through the [contact us](http://inheritance.ilmsummit.org/projects/inheritance/contactus.aspx) page?

**Comment by sarfrazeteam** [comment]
Yes but no reply from their side. Problem is that our client has seen this calculator and now he wants us to implement exactly like http://inheritance.ilmsummit.org/projects/inheritance/home.aspx. So we are stuck as some relationships are not working :(
